name: database
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies:
  dotenv: ^4.0.1
  mysql_client: ^0.0.27
  uuid: ^3.0.7
  models:
    path: ../../../models

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
