name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-0"
dependencies:
  bcrypt: ^1.1.3
  broadcast:
    path: ./packages/broadcast
  dart_frog: ^0.3.5
  dart_frog_web_socket: ^0.1.0-dev.3
  dart_jsonwebtoken: ^2.6.4
  database:
    path: ./packages/database
  dotenv: ^4.0.1
  models:
    path: ../packages/models
  validation:
    path: ./packages/validation

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
