name: user_repository
description: A new Dart project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5
  models:
    path: ../../../models

dev_dependencies:
  test: ^1.22.2
  very_good_analysis: ^3.1.0
