name: broadcast
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-0'

dependencies:
  dart_frog_web_socket: ^0.1.0-dev.3

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0
