name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.19.0-444.2.beta <3.0.0'

dependencies: 
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0  

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.21.0